services:
  backend:
    build: backend
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=gobookingdb
    networks:
      - react-spring
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=gobookingdb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend
    expose:
      - 3306
      - 33060
secrets:
  db-password:
    file: db/password.txt
networks:
  react-spring: {}
  spring-postgres: {}