services:
  backend:
    build:
      context: backend
      target: dev-envs
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=gobookingdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - react-spring
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/new-directory
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=gobookingdb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
  frontend:
    build:
      context: frontend
      target: dev-envs
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - react-spring
    depends_on:
      - backend
    expose:
      - 3306
      - 33060
secrets:
  db-password:
    file: db/password.txt
volumes:
  db-data:
networks:
  react-spring: {}
  spring-postgres: {}